## Oefeningen Python - Numpy - Pandas

## Gok het correcte getal

Maak een klasse voor een spel waarbij je een willekeurig getal moet gokken.
Deze klasse moet de volgende zaken doen:
* Een willekeurig getal tussen 0 en 20 genereren
* Een "start" functie hebben om het spel te starten
* In deze functie moet er herhaaldelijk om input gevraagd worden aan de gebruiker.
* De input moet vergeleken worden met het random getal. Als je input:
    * kleiner is dan het willekeurig getal, print je "Te laag"
    * groter is dan het willekeurig getal, print je "Te hoog"
    * gelijk is aan het getal, eindig je en print je dat je bent gewonnen
    * Gelijk is aan "Exit", eindig je en print je dat je verloren bent.
* Om te eindigen print je nog de volgende statistieken:
    * Hoeveel keer dat je gegokt hebt
    * Hoeveel je er gemiddeld naast zat
    
Vergeet zeker niet om de code te voorzien om het spel te starten

In [ ]:
from random import randint, random

class TestGame:
        
    randomNummer = 0
    aantalKerenGegokt = 0
    arrayErNaast = []

    def start():
        global randomNummer
        randomNummer = randint(1,20)

        global aantalKerenGegokt
        aantalKerenGegokt = 0

        global arrayErNaast
        arrayErNaast = []

        global printStatistiek

        while 1:
            invoer = input()
            aantalKerenGegokt +=  1
            verschilGokEnNummer = 0

            if int(invoer) > int(randomNummer):
                print("Te hoog!")
                verschilGokEnNummer = int(invoer) - int(randomNummer)
                arrayErNaast.append(verschilGokEnNummer)

            if int(invoer) < int(randomNummer):
                print("Te laag!")
                verschilGokEnNummer = int(randomNummer) - int(invoer)
                arrayErNaast.append(verschilGokEnNummer)

            if int(invoer) == int(randomNummer):
                print("Gewonnen! Het getal was " + str(randomNummer)),
                printStatistiek(),
                break

            if str(invoer) == "Exit":
                print("Spel afgesloten!"),
                printStatistiek(),
                break

    def printStatistiek():
        print("Aantal keer gegokt: " + str(aantalKerenGegokt)),
        gemiddeldeNaast = float(sum(arrayErNaast))/aantalKerenGegokt
        print("Je zat er gemiddeld met " + str(gemiddeldeNaast) + " naast.")

TestGame.start()

## Matrix bewerkingen

Maak functie voor het aanmaken een matrix waar elk waarde het product is van zijn rij en kolom index (bvb op rij 4 en kolom 5 moet er 20 staan). Deze functie moet als argument het aantal rij en aantal kolommen hebben.

Maak met behulp van deze functie een matrix "a" van 5 rijen en 7 kolommen aan.

In [114]:
import numpy as np

def matrixMaken(rijen, kolommen):
    a = np.empty((rijen, kolommen))
    for j in range(rijen):
        for i in range(kolommen):
            a[j,i] = (j+1)*(i+1)
    print(a)

matrixMaken(5,7)

[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]]


Maak een functie die met behulp van slicing de volgorde van de elementen in matrix "a" omdraait.

In [124]:
import numpy as np

def matrixMakenEnInversen(rijen, kolommen):
    a = np.empty((rijen, kolommen))
    for j in range(rijen):
        for i in range(kolommen):
            a[j,i] = (j+1)*(i+1)
    print(a)
    b = a[::-1, ::-1]
    print(b)


matrixMakenEnInversen(5,7)



[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]]
[[35. 30. 25. 20. 15. 10.  5.]
 [28. 24. 20. 16. 12.  8.  4.]
 [21. 18. 15. 12.  9.  6.  3.]
 [14. 12. 10.  8.  6.  4.  2.]
 [ 7.  6.  5.  4.  3.  2.  1.]]


Bereken de mean, median en standard deviation van elke kolom in matrix  "a".

In [138]:
import numpy as np

def matrixMaken(rijen, kolommen):
    a = np.empty((rijen, kolommen))
    for j in range(rijen):
        for i in range(kolommen):
            a[j,i] = (j+1)*(i+1)
    print(a)
    print("Gemiddelde: " + str(np.mean(a)))
    print("Mediaan: " + str(np.median(a)))
    print("Standaardafwijking: " + str(np.std(a)))

matrixMaken(5,7)



[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]]
Gemiddelde: 12.0
Mediaan: 10.0
Standaardafwijking: 8.717797887081348


Bereken hoeveel elementen in matrix "a" groter zijn dan 20

In [145]:
import numpy as np

def matrixMaken(rijen, kolommen):
    a = np.empty((rijen, kolommen))
    for j in range(rijen):
        for i in range(kolommen):
            a[j,i] = (j+1)*(i+1)
    print(a)
    print(f"Er zijn: {(a[a>20]).size} elementen groter dan 20.")
    
matrixMaken(5,7)

[[ 1.  2.  3.  4.  5.  6.  7.]
 [ 2.  4.  6.  8. 10. 12. 14.]
 [ 3.  6.  9. 12. 15. 18. 21.]
 [ 4.  8. 12. 16. 20. 24. 28.]
 [ 5. 10. 15. 20. 25. 30. 35.]]
Er zijn: 6 elementen groter dan 20.


## Pandas

Maak een dataframe aan voor het bijhouden van de scores van studenten.
Hiervoor moeten er minstens drie kolommen zijn, namelijk naam van een student, naam van een vak en de bijhorende score. Voorzie minstens drie studenten die voor elk drie vakken een score hebben. (Minstens 9 rijen dus). De scores mogen zelf gekozen zijn maar zorg dat er minstens 1 vak is voor elke student dat overgedaan moet worden.

Op basis van dit dataframe gaan we nu een aantal zaken berekenen. Schrijf in de cellen de code om de gevraagde zaken te berekenen (dus enkel de eindwaarde is niet voldoende)
Bereken voor elk vak de gemiddelde waarde, variantie en standaard afwijking

Voor hoeveel vakken is elke student geslaagd? Hoeveel studenten zijn er geslaagd (Gemiddelde van hun vakken groter dan of gelijk aan 10)?

Voeg nu een kolom toe waarin het percentage van elke score berekend wordt. Wat is het vak met het hoogste percentage van elke student?

Er is een herkansing geweest en de drie studenten hebben elk 1 vak moeten overdoen. Maark hiervoon opnieuw een dataframe aan voeg het toe aan het vorige dataframe. Bepaal hierna opnieuw voor hoeveel vakken elke student geslaagd is (om conflicten te vermijden tussen eerste en tweede kans moeten de duplicaten verwijderd worden).